Fix AssignPublicIp and add integration test
aws/aws-parallelcluster pull request #3055
Opened 2021-07-29 23:47 UTC by chenwany

Signed-off-by: chenwany <chenwany@amazon.com>

**Please See** [Git Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions)

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-30 13:08 UTC, enrico-usai commented on cli/src/pcluster/schemas/cluster_schema.py
> +            raise ValidationError("AssignPublicIp can not be False for headnode.")
This is wrong. It can be False for example when the entire cluster is in a private subnet accessible through a bastion or Direct Connect.

2021-07-30 13:19 UTC, lukeseawalker requested changes
ENI must not be dropped, because it's in charge to keep the private IP of the head node and will allow us to enable the feature to replace the head node

2021-08-02 09:01 UTC, enrico-usai submitted a review, later dismissed

2021-08-02 13:35 UTC, enrico-usai commented
Unit tests are failing.

2021-08-03 07:59 UTC, enrico-usai approved these changes

2021-08-03 08:11 UTC, merged