Integ-tests: ensure EIP is not left over if VPC orInternet Gateway creation fails.
aws/aws-parallelcluster pull request #3942
Opened 2022-04-01 20:55 UTC by hanwen-pcluste

Signed-off-by: Hanwen <hanwenli@amazon.com>

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-01 21:00 UTC, charlesg3 requested changes

2022-04-01 21:00 UTC, charlesg3 commented on tests/integration-tests/network_template_builder.py
> +        # The following depends on ensure EIP is not left over if VPC orInternet Gateway creation fails.
`        # The following depends_on ensures that EIP is not left over if VPC or InternetGateway creation fails.`

2022-04-02 00:56 UTC, hanwen-pcluste commented on tests/integration-tests/network_template_builder.py
> +        # The following depends on ensure EIP is not left over if VPC orInternet Gateway creation fails.
Done

2022-04-02 01:08 UTC, charlesg3 approved these changes

2022-04-04 14:49 UTC, merged