Upgrade Smithy and OpenApi generator versions
aws/aws-parallelcluster pull request #4270
Opened 2022-08-16 09:31 UTC by demartinofra

### Description of changes
* Pin smithy-cli version used to build API spec: this to prevent build breaks when a new version of Smithy CLI is released
* Upgrade Smithy to version 1.23 and rebuild OpenApi spec
* Upgrade OpenApi generator to version 6.0.1
* Sync OpenApi model after upgrading generator and Smithy deps - generated with `./gradlew generatePythonServer`

### Tests
* Unit tests
* Diff between generated OpenAPI file and the one consumed by the CLI
```
❯ diff api/generated/python-server/pcluster/api/openapi/openapi.yaml cli/src/pcluster/api/openapi/openapi.yaml
8,9c8,9
< security:
< - aws.auth.sigv4: []
---
> # security:
> # - aws.auth.sigv4: []
150a151
>               x-body-name: create_cluster_request_content
424a426
>               x-body-name: update_cluster_request_content
585a588
>               x-body-name: update_compute_fleet_request_content
1268a1272
>               x-body-name: build_image_request_content
```

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-16 15:01 UTC, jdeamicis requested changes, later dismissed
Reviewed the content of the non-auto-generated code. Some small changes are required.

2022-08-16 15:01 UTC, jdeamicis commented on api/spec/smithy/build.gradle.kts
> +    val smithyVersion: String by project
Do we need the variable declaration twice?

2022-08-16 15:01 UTC, jdeamicis commented on api/spec/openapi/ParallelCluster.openapi.yaml
> -            format: int32
As discussed via voice: this needs checking.

2022-08-16 15:01 UTC, jdeamicis commented on api/client/resources/readme.md.diff
> +--- api/client/src/README.md.orig	2022-08-16 11:43:01.000000000 +0200
We should rename all the `*.diff` files used for patching to `*.patch`

2022-08-16 15:01 UTC, jdeamicis commented on api/README.md
> +6. Open a PR to review the changes to the API.
Further expand with more details or create internal runbook with detailed steps.

2022-08-18 16:09 UTC, demartinofra commented on api/spec/smithy/build.gradle.kts
> +    val smithyVersion: String by project
apparently yes, I could not find a way to reference it within the buildscript block without redefining

2022-08-31 13:46 UTC, demartinofra commented on api/spec/openapi/ParallelCluster.openapi.yaml
> -            format: int32
done

2022-08-31 13:49 UTC, demartinofra commented on api/client/resources/readme.md.diff
> +--- api/client/src/README.md.orig	2022-08-16 11:43:01.000000000 +0200
done

2022-08-31 13:49 UTC, demartinofra commented on api/README.md
> +6. Open a PR to review the changes to the API.
done

2022-09-07 10:11 UTC, EddyMM submitted a review, later dismissed

2022-09-07 13:44 UTC, EddyMM approved these changes

2022-09-07 14:13 UTC, merged