Add Iam resources to LoginNodes
aws/aws-parallelcluster pull request #5458
Opened 2023-07-07 10:59 UTC by hehe7318

### Description of changes
* Modify login_nodes_stack.py
  * add a function to add login node iam resources
  * add instance profile to LoginNodes Pool Launch Template
* Modify cdk_builder_utils.py
  * add CloudWatchAgentServerPolicy (AWS managed) and parallelcluster (Customer inline) policies to LoginNodes

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

2023-07-10 12:46 UTC, maurizp requested changes

2023-07-10 12:46 UTC, maurizp commented on cli/src/pcluster/templates/cdk_builder_utils.py
> +            ),
This seems to be a duplicated of the `CloudWatchAgentServerPolicy`: why do you need to duplicate it?

2023-07-10 12:47 UTC, maurizp commented on cli/src/pcluster/templates/login_nodes_stack.py
how did you test it?

2023-07-10 15:27 UTC, hehe7318 commented on cli/src/pcluster/templates/cdk_builder_utils.py
> +            ),
I have removed the duplicate policies. Thank you for reminding.

2023-07-10 15:29 UTC, hehe7318 commented on cli/src/pcluster/templates/login_nodes_stack.py
I tested by creating a test cluster and looked into the role to see if the policies were included. Should I create a unit test?

2023-07-10 16:08 UTC, hehe7318 commented on cli/src/pcluster/templates/login_nodes_stack.py
I have added unit tests for it.

2023-07-11 06:05 UTC, maurizp approved these changes

2023-07-11 14:14 UTC, merged