Thheinen/efs accesspoints
aws/aws-parallelcluster pull request #6381
Opened 2024-08-05 10:04 UTC by mapk-amazon

"Clone" of https://github.com/aws/aws-parallelcluster/pull/6359

### Description of changes
Add support to specify EFS access points per issue https://github.com/aws/aws-parallelcluster/issues/2337

### Tests
* Integration tests included in the `develop.yaml` as well as unit tests.

2024-08-09 14:09 UTC, dreambeyondorange requested changes
Sorry for the delay.  I think this PR looks great.  Thanks for the contribution.  I have a couple minor comments and once resolved I can approve!

2024-08-09 14:09 UTC, dreambeyondorange commented on cli/src/pcluster/schemas/cluster_schema.py
> +    )
Has this update support been tested?

2024-08-09 14:09 UTC, dreambeyondorange commented on cli/src/pcluster/validators/efs_validators.py
> +            )
This probably needs to reference the `file_system_id` param

2024-08-09 14:09 UTC, dreambeyondorange commented on cli/tests/pcluster/validators/test_efs_validators.py
> +def test_efs_mount_options_validator(
This test would need to be updated to reflect the `file_system_id` param above.

2024-08-09 17:18 UTC, mapk-amazon commented on cli/src/pcluster/schemas/cluster_schema.py
> +    )
Has not been tested. To be one the safe side I marked it as `unsupported` now.

2024-08-09 17:18 UTC, mapk-amazon commented on cli/src/pcluster/validators/efs_validators.py
> +            )
Replaced the wrong `name` by the `file-system-id`.

2024-08-09 17:18 UTC, mapk-amazon commented on cli/tests/pcluster/validators/test_efs_validators.py
> +def test_efs_mount_options_validator(
Replaced the wrong `name` by the `file-system-id`.

2024-08-09 18:02 UTC, dreambeyondorange submitted a review, later dismissed

2024-08-09 18:02 UTC, dreambeyondorange commented
Approved but you need to rebase

2024-08-10 10:30 UTC, mapk-amazon commented
Rebased to the latest develop. Needed to rewrite the history a bit... Should now be up-to-date.

2024-08-13 13:41 UTC, dreambeyondorange approved these changes, later dismissed

2024-08-14 19:27 UTC, dreambeyondorange approved these changes

2024-08-14 19:27 UTC, merged